version: '2'
services:
  dockbeat:
    image: ingensi/dockbeat
    stdin_open: true
    environment:
      PERIOD: ${input_period}
      DOCKER_SOCKET: ${input_socket}
      DOCKER_ENABLE_TLS: ${input_tls_enable}
      DOCKER_CA_PATH: ${input_tls_ca_path}
      DOCKER_CERT_PATH: ${input_tls_cert_path}
      DOCKER_KEY_PATH: ${input_tls_key_path}
    external_links:
    - ${elasticsearch_source}:elasticsearch
    tty: true
    volumes:
      /var/run/docker.sock:/var/run/docker.sock
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
      