version: '2'
volumes:
  esdatamasters:
    driver: rancher-nfs
services:
  elasticsearch-masters:
    mem_limit: 1073741824
    cap_add:
    - IPC_LOCK
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      bootstrap.memory_lock: 'true'
      cluster.name: docker-cluster
      discovery.zen.minimum_master_nodes: '1'
      discovery.zen.ping.unicast.hosts: elasticsearch-masters
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - esdatamasters:/usr/share/elasticsearch/data
    ports:
    - 9200:9200/tcp
    labels:
      io.rancher.container.hostname_override: container_name



