name: Service Layer 3 ELK Config Loads    
description: Loaders for Elk Configs
version: 1.0.0.1
category: ELK
maintainer: "Chris Callanan chris.callanan@itaas.dimensiondata.com"
minimum_rancher_version: v1.2.3
projectURL: https://rancherlab.itaas-cloud.com