version: '2'
services:
  splunk-main:
    image: splunk/splunk:latest
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_USER: root
    stdin_open: true
    tty: true
    ports:
    - 8000:8000/tcp
    labels:
      io.rancher.container.pull_image: always