name: NginX for Rancher 1.0
description: |
  NginX for Rancher Server
version: 1.0.0.0
category: NginX
maintainer: "Chris Callanan calloes@gmail.com"
minimum_rancher_version: v1.2.3
projectURL: https://rancherlab.itaas-cloud.com