version: '2'
volumes:
  sql-server-data:
    external: true
    driver: rancher-nfs
services:
  sql-data:
    image: microsoft/mssql-server-linux:latest
    stdin_open: true
    volumes:
    - sql-server-data:/Documents
  sql-server:
    image: microsoft/mssql-server-linux:latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: DevAdmin123
      MSSQL_PID: Developer
    stdin_open: true
    tty: true
    volumes_from:
    - sql-data
    ports:
    - 1433:1433/tcp
    command:
    - --cap-add
    - SYS_PTRACE
    labels:
      io.rancher.sidekicks: sql-data