version: '2'
services:
  sql-data:
    image: alpine:latest
    entrypoint:
      - /bin/true
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    network_mode: none
    labels:
        io.rancher.container.hostname_override: container_name
        io.rancher.container.start_once: true
    volumes:
    - /var/opt/mssql/data
  sql-server:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: DevAdmin123
      MSSQL_PID: Developer
    stdin_open: true
    tty: true
    volumes_from:
    - sql-data
    ports:
    - 1433:1433/tcp
    labels:
      io.rancher.sidekicks: sql-data