version: '2'
volumes:
  sql-server-data:
    external: true
    driver: rancher-nfs
services:
  sql-data:
    environment:
      ACCEPT_EULA: Y
    image: microsoft/mssql-server-linux:latest
    network_mode: none
    labels:
        io.rancher.container.hostname_override: container_name
        io.rancher.container.start_once: true
    volumes:
    - sql-server-data:/Documents
  sql-server:
    image: microsoft/mssql-server-linux:latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: DevAdmin123
      MSSQL_PID: Developer
    stdin_open: true
    tty: true
    volumes_from:
    - sql-data
    ports:
    - 1433:1433/tcp
    labels:
      io.rancher.sidekicks: sql-data