version: '2'
volumes:
  sql-server-data:
    external: true
    driver: rancher-nfs
services:
  sql-server:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: DevAdmin123
      MSSQL_PID: Developer
    stdin_open: true
    tty: true
    volumes:
    - sql-server-data:/var/opt/mssql/data
    ports:
    - 1433:1433/tcp
    labels:
      io.rancher.sidekicks: sql-data