version: '2'
services:
  dd-elastic-load:
    image: artifactory.devops.itaas-cloud.com:6553/elk-config:latest
    stdin_open: true
    environment:
      ELASTIC_HOST: es-ingest.es-master:9200
    tty: true
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      