version: '2'
services:
  dd-elastic-load:
    image: artifactory.devops.itaas-cloud.com:6553/elk-config:latest
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: true