version: '2'
services:
  consul-base:
    image: consul:0.8.1
    ports:
      - 8500:8500/tcp
      - 53:8600/udp
      - 400:8400/tcp
      - 8301:8301/tcp
      - 8302:8302/tcp
    entrypoint:
      - /opt/rancher/bin/start_consul.sh
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: consul-data
      io.rancher.scheduler.global: 'true'
    volumes_from:
      - consul-data
  consul-data:
    image: alpine:latest
    entrypoint:
      - /bin/true
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    volumes:
      - /consul/data
  #consul:
  #  image: 
  #  labels:
  #    io.rancher.container.hostname_override: container_name
  #    io.rancher.sidekicks: consul-base,consul-data
  #  volumes_from:
  #    - consul-data
  #{