name: dockbeat
description: Dimension Data Research DockBeat for Rancher
version: 1.0.0.1
category: Elastic
maintainer: "Chris Callanan calloes@gmail.com"
minimum_rancher_version: v1.2.3
projectURL: https://rancherlab.itaas-cloud.com