name: Consul Cluster 0.8.1
description: |
  Consul
version: 1.0.0.0
category: Clustering
maintainer: "Chris Callanan calloes@gmail.com"
minimum_rancher_version: v1.2.3
projectURL: https://rancherlab.itaas-cloud.com