version: '2'
services:
  sql-data:
    image: microsoft/nanoserver
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    network_mode: none
    volumes:
    - c:\temp
  sql-server:
    image: microsoft/microsoft/mssql-server-windows
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: DevAdmin123
      MSSQL_PID: Developer
    stdin_open: true
    tty: true
    volumes_from:
    - sql-data
    ports:
    - 1433:1433/tcp
    labels:
      io.rancher.sidekicks: sql-data