logstash-indexer-config:
  restart: always
  image: artifactory.devops.itaas-cloud.com:6553/logstash-config:latest
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
redis:
  restart: always
  tty: true
  image: redis:3.2.6-alpine
  stdin_open: true
  labels:
    io.rancher.container.hostname_override: container_name
logstash-indexer:
  restart: always
  tty: true
  volumes_from:
  - logstash-indexer-config
  command:
  - logstash
  - -f
  - /etc/logstash
  image: docker.elastic.co/logstash/logstash:5.5.2
  links:
  - redis:redis
  external_links:
  - ${elasticsearch_link}:elasticsearch
  stdin_open: true
  labels:
    io.rancher.sidekicks: logstash-indexer-config
    io.rancher.container.hostname_override: container_name
logstash-collector-config:
  restart: always
  image: artifactory.devops.itaas-cloud.com:6553/logstash-config:latest
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
logstash-collector:
  restart: always
  tty: true
  links:
  - redis:redis
  ports:
  - "5000/udp"
  - "6000/tcp"
  volumes_from:
  - logstash-collector-config
  command:
  - logstash
  - -f
  - /etc/logstash
  image: docker.elastic.co/logstash/logstash:5.5.2
  stdin_open: true
  labels:
    io.rancher.sidekicks: logstash-collector-config
    io.rancher.container.hostname_override: container_name
