version: '2'
services:
  splunk-main:
    image: artifactory.devops.itaas-cloud.com:6553/nginx-consultemplate:latest
    environment:
      ELASTIC_HOST: http://elasticsearch:8200
    labels:
      io.rancher.container.pull_image: always