version: '2'
services:
  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - docker_elk
    volumes:
      - ELKCONFIG:/root/elk-config
      - ELKDATA:/usr/share/elasticsearch/data
  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/ --config.reload.automatic
    volumes:
      #- ./logstash/config:/etc/logstash/conf.d
      - LOGSTASHCONFD:/etc/logstash/conf.d
      #- C:/Development/gitlabs/elk:/root/elk-config need to include from elk
    ports:
      - "5044:5044"
      - "5045:5045"
    networks:
      - docker_elk
    environment:
      - LS_HEAP_SIZE=1024
      - ES_HOST=elasticsearch
    depends_on:
      - elasticsearch
  kibana:
    build: kibana/
    volumes:
      - KIBANACONFIG:/etc/kibana/
      #- C:/Development/gitlabs/elk:/root/elk-config
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
networks:
  docker_elk:
    driver: bridge