version: '2'
services:
  sl3-elk-config:
    image: artifactory.devops.itaas-cloud.com:6553/elk-config:latest
    environment:
      ELASTIC_HOST: http://elasticsearch:8200
    labels:
      io.rancher.container.pull_image: always